"""fastapi-db

Revision ID: 323400e32e0e
Revises: 2ace795638bd
Create Date: 2021-11-01 10:05:35.912581

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '323400e32e0e'
down_revision = '2ace795638bd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
